feat(test action): Test Example Mod

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,6 +7,19 @@ on:
       - '**'
 
 jobs:
+  fetch-geode-version:
+    name: Get Geode Version
+    runs-on: ubuntu-latest
+    outputs:
+      geode_ver: ${{ steps.get_version.outputs.geode_version }}
+    steps:
+    - name: Get latest release tag
+      id: get_version
+      run: |
+        # Get latest Geode version
+        GEODE_VERSION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/geode-sdk/geode/releases/latest | jq -r .tag_name)
+        GEODE_VERSION=${GEODE_VERSION#v}
+        echo "geode_version=$GEODE_VERSION" >> $GITHUB_OUTPUT
   build:
     strategy:
       fail-fast: false
@@ -25,26 +38,60 @@ jobs:
 
     name: ${{ matrix.config.name }}
     runs-on: ${{ matrix.config.os }}
+    needs: ['fetch-geode-version']
 
     steps:
       - uses: actions/checkout@v4
 
       - uses: actions/checkout@v4
         with:
-          repository: geode-sdk/textureldr
-          path: textureldr
+          repository: geode-sdk/example-mod
+          path: example-mod-test
+
+      - name: Modify Example Mod files
+        shell: bash
+        run: |
+          GEODE_VERSION="${{ needs.fetch-geode-version.outputs.geode_ver }}"
+          if [ $GEODE_VERSION == null ]; then 
+            echo "Could not get the latest version for testing"
+            exit 1;
+          fi
+
+          # Set path of mod.json file
+          mod_json_path="example-mod-test/mod.json"
+
+          # Read the current mod.json content
+          mod_json=$(cat $mod_json_path)
+
+          # Replace the placeholders
+          updated_mod_json=$(echo "$mod_json" | jq \
+            --arg geode_version "$GEODE_VERSION" \
+            --arg mod_id "geode.example" \
+            --arg mod_name "Example Mod" \
+            --arg mod_version "0.0.0" \
+            --arg mod_description "The example Geode mod!" \
+            --argjson developer "Geode Team" \
+            '.geode = $geode_version |
+            .id = $mod_id |
+            .name = $mod_name |
+            .version = $mod_version |
+            .description = $mod_description |
+            .developer = $developer')
+
+          # Write updated_mod_json variable contents to mod.json file
+          echo $updated_mod_json > $mod_json_path
 
       - name: Build the mod
         uses: ./
         with:
           # sdk: nightly
           build-config: RelWithDebInfo
-          path: textureldr
+          path: example-mod-test
           combine: true
           target: ${{ matrix.config.target }}
 
   package:
-    name: Package both builds
+    name: Package builds
     runs-on: ubuntu-latest
     needs: ['build']
 
